version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    # restart: always
    ports:
      - 5444:5444
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - .docker/ignite:/data/postgres
    network_mode: host
    command: -p 5444
  app:
    build: .
    container_name: rentx
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  ignite:
    driver: local
